# Generated by Django 2.2.7 on 2019-11-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='decription',
            new_name='description',
        ),
    ]
