# Generated by Django 2.2.7 on 2019-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20191121_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
