# Generated by Django 2.2.7 on 2019-11-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20191127_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendee',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Events'),
        ),
    ]
