# Generated by Django 2.2.7 on 2019-11-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_atendee_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendee',
            name='looking_for',
            field=models.CharField(max_length=100),
        ),
    ]
