# Generated by Django 2.2.7 on 2019-11-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20191127_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendee',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
